config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'
  get 'hello/design' => 'hello#design'

  resources :users, only: [:show]
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :shops do
    resources :comments, only: [:create, :destroy] # コメントはshopに紐付くため、ネストする
  end
  resources :hashtags, only: [:show] # ハッシュタグの詳細ページ（ツイート一覧）
  root 'hello#index'

  # ルーレット機能を呼び出すためのルート
  get 'post/roulette', to: 'post#roulette', as: 'roulette_post'
  # 必要に応じて、ルートのルート（例: root 'post#roulette'）を設定することもできます。

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_many :tweet_hashtags, dependent: :destroy
  has_many :hashtags, through: :tweet_hashtags
  has_one_attached :image
  
  #tweetsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy

private

  def save_hashtags
    # 本文からハッシュタグを抽出する正規表現
    # 例: #hogehoge の形式にマッチ
    extracted_hashtags = self.content.scan(/[#＃][A-Za-z0-9_]+/).map do |tag|
      tag.delete('#').downcase # # を削除し、小文字に変換
  end

    # 既存のハッシュタグを一旦クリア（更新時の重複保存防止）
  self.hashtags.clear if self.hashtags.present?

  extracted_hashtags.uniq.each do |tag_name|
    hashtag = Hashtag.find_or_create_by(name: tag_name)
    self.hashtags << hashtag unless self.hashtags.include?(hashtag)
  end
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @tweets = Tweet.all
    search = params[:search]
    if search.present?
      @tweets = @tweets.joins(:user).where("body LIKE ? OR name LIKE ?", "%#{search}%", "%#{search}%")
    end
    @tweets = @tweets.page(params[:page]).per(3)
  
    if params[:tag_ids]
      @tweets = []
      params[:tag_ids].each do |key, value|      
        @tweets += Tag.find_by(name: key).tweets if value == "1"
      end
      @tweets.uniq!
    end

    if params[:tag]
      Tag.create(name: params[:tag])
    end
  
  end

  def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.new(tweet_params)
    tweet.user_id = current_user.id
    if tweet.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments
    @comment = Comment.new
  end
  

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body,:image,tag_ids: [])
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body, :size => 140 %> 
  <%= f.submit "編集する" %>
<% end %>

app/views/tweets/index.html.erb
<h1>GeekTwitter</h1>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<h3>Tweet一覧</h3>
<h3>投稿を検索</h3>
<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>

<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<%= link_to "新規投稿へ",  new_tweet_path %>
<%= link_to 'ルーレット', roulette_post_path %>
<%= page_entries_info @tweets %>
<%= paginate @tweets %>

<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
      <% Tag.all.each do |t| %>
        <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
      <% end %>
      <%= submit_tag '検索' %>
<% end %>

  <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
      <%= text_field_tag :tag %>
      <%= submit_tag 'タグを追加' %>
  <% end %>


<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">


      <% if t.image.attached? %>
        <%= image_tag t.image, size: '250x200'%>
      <% end %>
      <% if t.user.image.attached? %>
          <%= image_tag  t.user.image, size: '250x200'%>
      <% end %>
      <%= t.body %>


      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), data: { turbo_method: :delete } do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), data: { turbo_method: :post }  do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% end %>
      <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
      <% end %>
      <%= link_to t.user.name, user_path(t.user.id) %>
      <%= t.user.email %> 
      <%= t.created_at %>
      <%= link_to "詳細へ", tweet_path(t.id) %>
      

      <% if user_signed_in? && current_user.id == t.user_id %>
        <%= link_to "編集する", edit_tweet_path(t.id) %>
        <%= link_to "削除する", tweet_path(t.id), method: :delete %>
      <% end %>
    
    
    </div>
  <% end %>
</div>

app/views/tweets/new.html.erb
<h1>GeekTwitter</h1>
<h3>新規Tweet</h3>
<%= form_for @tweet do |f| %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %>
    
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  
  <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
  </div>

  <%= f.submit "Tweetする" %>
<% end %>
<%= link_to "Tweet一覧に戻る", tweets_path %>

app/views/tweets/show.html.erb
<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.body %></p>
  <p><%= @tweet.created_at %></p>
  <p>
  <%= raw sanitize_with_hashtags(@tweet.body) %>
  </p>

    <% if user_signed_in? %>
      <% if current_user.already_liked?(@tweet) %>
        <%= link_to tweet_like_path(id: @tweet.id, tweet_id: @tweet.id), data: { turbo_method: :delete } do %>
          <i class="fas fa-heart"></i><%= @tweet.likes.count %>
        <% end %>
      <% else %>
        <%= link_to tweet_likes_path(id: @tweet.id, tweet_id: @tweet.id), data: { turbo_method: :post }  do %>
          <i class="far fa-heart"></i><%= @tweet.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <i class="far fa-heart"></i><%= @tweet.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_tweet_path(@tweet.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @tweet.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>


<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% @tweet.tags.each do |tag| %>
    <span><%= tag.name %></span>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "Tweet一覧に戻る", tweets_path %>